version: '3.7'
services:  
  official:
    container_name: official
    build: ./        
    ports:
      - 8005:3000         
    working_dir: /usr/src/app
    entrypoint: "pnpm start"
    networks:
      - shared   
    restart: always
networks:
  shared:
    external: true