version: '3.7'

services:  
  official_dev:
    container_name: official_dev
    build: ./        
    ports:
      - 8007:3000         
    working_dir: /usr/src/app
    entrypoint: "pnpm start"
    networks:
      - shared   
networks:
  shared:
    external: true